name: Go Build and Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**.md"

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.24'
          cache: true

      - name: Build
        run: make build

      - name: Test
        run: make test
