name: Schema Validation
on: [push, pull_request]
jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
      - name: Generate schema
        run: make schema
      - name: Check for schema changes
        run: |
          if ! git diff --quiet schema.json; then
            echo "Error: schema.json is out of date. Please run 'make schema' and commit the changes."
            git diff schema.json
            exit 1
          fi
